# DevContainers
services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace/
    working_dir: /workspace/
    ports:
      - "3000:3000"
      - "3001:3001"
    command: sh -c "yarn start"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  auth-node_modules:
