# DevContainers
services:
  app:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../:/workspace
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx-test-root:/usr/share/nginx/html
