events {}

http {
    log_format upstreamlog '[$time_local] [$remote_addr $host] '
                           '[$upstream_addr $upstream_status $proxy_add_x_forwarded_for] $request';

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        access_log /var/log/nginx/access.log upstreamlog;

        location = /_auth {
            internal;
            proxy_pass http://app:3000/auth/api/auth;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Cookie $http_cookie;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ^~ /private/ {
            auth_request /_auth;
            error_page 401 =302 /auth/login.html;
            try_files $uri $uri/ =404;
        }

        location ^~ /auth/ {
            proxy_pass http://app:3000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
